behaviors:
  MazeAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 1000
      learning_rate: 1.0e-5
      beta: 5.0e-2
      epsilon: 0.1
      lambd: 0.95
      num_epoch: 2
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1200000
    time_horizon: 64
    summary_freq: 10000